output-format: text

strictness: veryhigh
test-warnings: true
doc-warnings: false
member-warnings: true

uses:
  - django

pep8:
  full: true
  disable:
    - D100
    - D101
    - D102
    - D103
    - D105
    - D205
    - D400
    - N811  # constant imported as non constant, breaks for Django's `Q`
    - N802  # function name should be lowercase, breaks for some Django test methods
  options:
    max-line-length: 100

pyflakes:
  disable:
    - F999

pylint:
  disable:
    - too-many-arguments
    - invalid-name
    - no-member
    - no-self-use
    - protected-access
    - super-init-not-called
    - too-few-public-methods
    - too-many-instance-attributes
  options:
    max-line-length: 100
    max-parents: 15

dodgy:
  run: true

ignore-paths:
  - node_modules
  - venv
  - env
  - docs

ignore-patterns:
  - .+/migrations/.+
  - tests/settings.py
  - setup.py
  - runtests.py
  - manage.py
  - .tox/.+
